"""YARA rule rendering and file writing for signature extraction."""
import hashlib
import re
from pathlib import Path
from typing import Any, List, Tuple


def _yara_escape_str_literal(s: str):
    """Escape a string for use inside a YARA double-quoted literal."""
    s = s.replace("\\", r"\\")
    s = s.replace('"', r'\"')
    s = s.replace("\n", r"\n")
    s = s.replace("\r", r"\r")
    s = s.replace("\t", r"\t")
    return s


def _yara_word_ngram_regex(pattern: str):
    """Build a word-boundary regex for a whitespace-separated n-gram."""
    tokens = pattern.split()
    body = "\\s+".join(re.escape(t) for t in tokens)
    return f"(^|\\s){body}(\\s|$)"


def _pattern_to_yara_string(pattern: str):
    """Return (identifier, yara_string_declaration).

    - Word n-grams (1–4 tokens, all alphanumeric): whitespace-bounded regex.
    - Everything else: plain double-quoted literal.
    """
    tokens = pattern.split()
    if 1 <= len(tokens) <= 4 and all(tok.isalnum() for tok in tokens):
        regex = _yara_word_ngram_regex(pattern)
        return "$re", f"$re = /{regex}/ nocase"
    lit = _yara_escape_str_literal(pattern)
    return "$s", f'$s = "{lit}" nocase'


def _yara_meta_value(v: Any):
    """Render a value as a YARA meta literal.

    YARA supports integers and quoted strings; floats are stored as strings.
    """
    if isinstance(v, bool):
        return str(v).lower()
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return f'"{v}"'
    return f'"{_yara_escape_str_literal(str(v))}"'


def _pattern_digest(pattern: str):
    """Return a short deterministic hex ID for *pattern*."""
    h = hashlib.blake2b(pattern.encode("utf-8"), digest_size=6)
    return h.hexdigest()


def _render_rule(
    rule_name: str,
    tags: List[str],
    pattern: str,
    ident: str,
    decl: str,
    meta: List[Tuple[str, Any]],
):
    tag_str = f" : {' '.join(tags)}" if tags else ""
    lines = [
        f"rule {rule_name}{tag_str} {{",
        "    meta:",
        f'        pattern = "{_yara_escape_str_literal(pattern)}"',
    ]
    for k, v in meta:
        lines.append(f"        {k} = {_yara_meta_value(v)}")
    lines += [
        "    strings:",
        f"        {decl}",
        "    condition:",
        f"        {ident}",
        "}",
    ]
    return "\n".join(lines)


def write_yara_rules(
    out_path: Path,
    rule_prefix: str,
    signatures: List[dict],
    meta_keys: List[str],
):
    """Render signatures as YARA rules and write to out_path."""
    lines: List[str] = [
        "/*",
        "  AUTO-GENERATED FILE",
        "  Generated by: scripts/extract_signature_patterns.py",
        "  Source: datasets/barrikada.csv",
        "*/",
        "",
    ]
    for idx, sig in enumerate(signatures, start=1):
        pattern = str(sig["pattern"]).strip()
        if not pattern:
            continue
        digest    = _pattern_digest(pattern)
        rule_name = f"{rule_prefix}{digest}_{idx:04d}"
        ident, decl = _pattern_to_yara_string(pattern)
        meta = [(k, sig[k]) for k in meta_keys if k in sig]
        lines.append(
            _render_rule(
                rule_name=rule_name,
                tags=["extracted"],
                pattern=pattern,
                ident=ident,
                decl=decl,
                meta=meta,
            )
        )
        lines.append("")

    out_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
